//! Column `DEFAULT` persistence + `SERIAL` columns.
//!
//! A column default is the expression used to fill a column omitted from an `INSERT`. Defaults live
//! in an engine-scoped SQL-layer catalog `nusadb_column_defaults`, mirroring the trigger/view catalog
//! pattern — the storage treaty deliberately has no column-default slot (see the note in
//! `nusadb_core::engine`), so they stay in the SQL layer. Created lazily; no treaty change.
//!
//! The default's canonical SQL text is stored per `(table, column)` and re-parsed at insert time into
//! a typed expression evaluated against an empty row (a default references no other column).
//!
//! A `SERIAL` column reuses the same catalog: its "default" is a [`SERIAL_PREFIX`] sentinel carrying
//! its backing sequence name, which the insert path resolves to a `nextval` ([`ColumnFill::Serial`])
//! rather than a pure expression — the sequence advance needs the engine, which a `DEFAULT`
//! expression's row-only evaluation does not have.
#![allow(clippy::wildcard_imports)]
#![allow(
    clippy::redundant_pub_crate,
    reason = "serial_default_sql / sequence_name are pub(crate) so the analyzer can build the \
              SERIAL sentinel; the module stays crate-private"
)]

use super::*;

/// Engine-scoped catalog of column defaults. Three text columns: `(table, column, default_sql)`.
const DEFAULT_CATALOG: &str = "nusadb_column_defaults";

/// The three-text-column schema of [`DEFAULT_CATALOG`].
const DEFAULT_CATALOG_SCHEMA: [ColumnType; 3] =
    [ColumnType::Text, ColumnType::Text, ColumnType::Text];

/// Prefix marking a stored "default" that is actually a `SERIAL` column's backing sequence rather
/// than an SQL expression. The remainder is the sequence name. Chosen to never collide with
/// real SQL (a leading NUL is not a valid default expression).
const SERIAL_PREFIX: &str = "\u{0}serial:";

/// Like [`SERIAL_PREFIX`], but for a `GENERATED ALWAYS AS IDENTITY` column (#9a). It still
/// auto-fills from its backing sequence when omitted, but — unlike `SERIAL` / `GENERATED BY DEFAULT` —
/// it rejects an explicit value at `INSERT`.
const IDENTITY_ALWAYS_PREFIX: &str = "\u{0}identity_always:";

/// Prefix marking a stored "default" that is actually a `GENERATED ALWAYS AS (<expr>) STORED` computed
/// column. The remainder is the generation expression's SQL text, which — unlike a `DEFAULT` —
/// references this table's other columns, so it is analyzed against the table scope and re-evaluated
/// against each fully-populated row. Always applied (and an explicit value for the column is rejected).
const GENERATED_PREFIX: &str = "\u{0}generated:";

/// The catalog default-text for a `GENERATED ALWAYS AS (<expr>) STORED` column.
#[must_use]
pub(crate) fn generated_default_sql(expr_sql: &str) -> String {
    format!("{GENERATED_PREFIX}{expr_sql}")
}

/// If `default_sql` marks a generated column, its generation-expression SQL; otherwise `None`.
pub(super) fn generated_expr(default_sql: &str) -> Option<&str> {
    default_sql.strip_prefix(GENERATED_PREFIX)
}

/// The column ordinals of `table`'s STORED generated columns. Their stored values are recomputed
/// from other columns on every write ([`column_fills`] → `ColumnFill::Generated`), so an `UPDATE`
/// that assigns a generated column's dependency changes the generated column even though it is not
/// in the assignment list. A caller reasoning about which columns an UPDATE can change (uniqueness /
/// index maintenance) must fold these in whenever anything is assigned, or it will wrongly treat a
/// generated key/index column as untouched.
pub(super) fn generated_column_ordinals(
    table: &TableSchema,
    engine: &dyn StorageEngine,
    txn: TxnId,
) -> Result<Vec<usize>, Error> {
    let stored = load_defaults(&catalog_key(&table.schema, &table.name), engine, txn)?;
    let mut ordinals = Vec::new();
    for (column, sql) in stored {
        if generated_expr(&sql).is_some()
            && let Some((index, _)) = table
                .columns
                .iter()
                .enumerate()
                .find(|(_, c)| c.name == column)
        {
            ordinals.push(index);
        }
    }
    Ok(ordinals)
}

/// The catalog default-text for a `SERIAL` / `GENERATED BY DEFAULT AS IDENTITY` column backed by
/// sequence `seq` (an explicit value is accepted).
#[must_use]
pub(crate) fn serial_default_sql(seq: &str) -> String {
    format!("{SERIAL_PREFIX}{seq}")
}

/// The catalog default-text for a `GENERATED ALWAYS AS IDENTITY` column backed by sequence `seq` (an
/// explicit value is rejected — #9a).
#[must_use]
pub(crate) fn identity_always_default_sql(seq: &str) -> String {
    format!("{IDENTITY_ALWAYS_PREFIX}{seq}")
}

/// The deterministic backing-sequence name for `table.column`'s `SERIAL`.
#[must_use]
pub(crate) fn sequence_name(table: &str, column: &str) -> String {
    format!("{table}_{column}_seq")
}

/// The `nusadb_column_defaults` row key for a table. The default catalog is keyed by table
/// name only, so a non-`public` schema must be folded into the key to keep two same-named tables in
/// different schemas from overwriting each other's defaults. `public` keeps the bare name so existing
/// rows (and the `public`-only paths: `ALTER ... SET DEFAULT`, SERIAL) are byte-for-byte unchanged.
#[must_use]
pub(super) fn catalog_key(schema: &str, name: &str) -> String {
    if schema == nusadb_core::PUBLIC_SCHEMA {
        name.to_owned()
    } else {
        format!("{schema}.{name}")
    }
}

/// If `default_sql` is a `SERIAL` / `GENERATED ... AS IDENTITY` sentinel (either variant), the backing
/// sequence name; otherwise `None`. Both variants auto-fill from the sequence when the column is
/// omitted — they differ only in whether an *explicit* value is allowed.
pub(super) fn serial_sequence(default_sql: &str) -> Option<&str> {
    default_sql
        .strip_prefix(SERIAL_PREFIX)
        .or_else(|| default_sql.strip_prefix(IDENTITY_ALWAYS_PREFIX))
}

/// How an omitted column is filled on `INSERT`: either by evaluating a `DEFAULT` expression, or by
/// advancing a `SERIAL` column's backing sequence.
pub(super) enum ColumnFill {
    /// Evaluate this typed `DEFAULT` expression per row.
    Expr(crate::planner::TypedExpr),
    /// Advance this sequence (`nextval`) for each row. `always` marks a `GENERATED ALWAYS AS IDENTITY`
    /// column, which rejects an explicit value (#9a).
    Serial {
        id: nusadb_core::SequenceId,
        always: bool,
    },
    /// Evaluate this `GENERATED ALWAYS AS (<expr>) STORED` expression against the fully-populated row
    /// (it references the row's other columns), in a second pass after every other column is filled.
    /// Always applied; an explicit value for the column is rejected at INSERT/UPDATE.
    Generated(crate::planner::TypedExpr),
}

/// Look up the column-default catalog, creating it lazily if it does not exist yet.
fn ensure_default_catalog(
    engine: &dyn StorageEngine,
    txn: TxnId,
) -> Result<nusadb_core::TableId, Error> {
    if let Some(schema) = engine.lookup_table_as_of(txn, DEFAULT_CATALOG)? {
        return Ok(schema.id);
    }
    let columns = ["table", "column", "default_sql"]
        .into_iter()
        .map(|name| ColumnDef {
            name: name.to_owned(),
            ty: ColumnType::Text,
            nullable: false,
        })
        .collect();
    let def = TableDef {
        schema: "public".to_owned(),
        name: DEFAULT_CATALOG.to_owned(),
        columns,
    };
    Ok(engine.create_table(txn, &def)?)
}

/// Persist `defaults` (each `(column, default SQL)`) for `table`, first removing any prior rows for it
/// so a recreated table does not inherit stale defaults. A no-op when `defaults` is empty and
/// the catalog does not exist yet.
pub(super) fn store_defaults(
    table: &str,
    defaults: &[(String, String)],
    engine: &dyn StorageEngine,
    txn: TxnId,
) -> Result<(), Error> {
    if defaults.is_empty() {
        // Nothing to add; only clear stale rows if the catalog already exists.
        delete_defaults_for_table(table, engine, txn)?;
        return Ok(());
    }
    let cat = ensure_default_catalog(engine, txn)?;
    delete_defaults_for_table(table, engine, txn)?;
    for (column, sql) in defaults {
        let row = [
            ast::Value::Text(table.to_owned()),
            ast::Value::Text(column.clone()),
            ast::Value::Text(sql.clone()),
        ];
        engine.insert(txn, cat, &row::encode(&row, &DEFAULT_CATALOG_SCHEMA)?)?;
    }
    Ok(())
}

/// `ALTER COLUMN … SET DEFAULT <expr>`: upsert one column's default, replacing any prior
/// default for that `(table, column)`.
pub(super) fn set_default(
    table: &str,
    column: &str,
    default_sql: &str,
    engine: &dyn StorageEngine,
    txn: TxnId,
) -> Result<(), Error> {
    let cat = ensure_default_catalog(engine, txn)?;
    delete_one(table, column, engine, txn)?;
    let row = [
        ast::Value::Text(table.to_owned()),
        ast::Value::Text(column.to_owned()),
        ast::Value::Text(default_sql.to_owned()),
    ];
    engine.insert(txn, cat, &row::encode(&row, &DEFAULT_CATALOG_SCHEMA)?)?;
    Ok(())
}

/// `ALTER COLUMN … DROP DEFAULT`: remove one column's default (a no-op if it has none).
pub(super) fn drop_default(
    table: &str,
    column: &str,
    engine: &dyn StorageEngine,
    txn: TxnId,
) -> Result<(), Error> {
    delete_one(table, column, engine, txn)
}

/// Remove the single `(table, column)` default row, if present.
fn delete_one(
    table: &str,
    column: &str,
    engine: &dyn StorageEngine,
    txn: TxnId,
) -> Result<(), Error> {
    let Some(cat) = engine.lookup_table_as_of(txn, DEFAULT_CATALOG)? else {
        return Ok(());
    };
    let mut victims = Vec::new();
    let mut scan = engine.scan(txn, cat.id)?;
    while let Some((tid, bytes)) = scan.try_next()? {
        let row = row::decode(&bytes, &DEFAULT_CATALOG_SCHEMA)?;
        if matches!((row.first(), row.get(1)),
            (Some(ast::Value::Text(t)), Some(ast::Value::Text(c))) if t == table && c == column)
        {
            victims.push(tid);
        }
    }
    for tid in victims {
        engine.delete(txn, cat.id, tid)?;
    }
    Ok(())
}

/// Remove every column-default row for `table` (used on `DROP TABLE` and before re-persisting).
pub(super) fn delete_defaults_for_table(
    table: &str,
    engine: &dyn StorageEngine,
    txn: TxnId,
) -> Result<(), Error> {
    let Some(cat) = engine.lookup_table_as_of(txn, DEFAULT_CATALOG)? else {
        return Ok(());
    };
    let mut victims = Vec::new();
    let mut scan = engine.scan(txn, cat.id)?;
    while let Some((tid, bytes)) = scan.try_next()? {
        let row = row::decode(&bytes, &DEFAULT_CATALOG_SCHEMA)?;
        if matches!(row.first(), Some(ast::Value::Text(t)) if t == table) {
            victims.push(tid);
        }
    }
    for tid in victims {
        engine.delete(txn, cat.id, tid)?;
    }
    Ok(())
}

/// Load `table`'s defaults as `(column, default SQL)` pairs. The fast path (no catalog, or no default
/// for `table`) costs a single catalog lookup.
pub(super) fn load_defaults(
    table: &str,
    engine: &dyn StorageEngine,
    txn: TxnId,
) -> Result<Vec<(String, String)>, Error> {
    let Some(cat) = engine.lookup_table_as_of(txn, DEFAULT_CATALOG)? else {
        return Ok(Vec::new());
    };
    let mut out = Vec::new();
    let mut scan = engine.scan(txn, cat.id)?;
    while let Some((_, bytes)) = scan.try_next()? {
        let row = row::decode(&bytes, &DEFAULT_CATALOG_SCHEMA)?;
        if let (Some(ast::Value::Text(t)), Some(ast::Value::Text(col)), Some(ast::Value::Text(sql))) =
            (row.first(), row.get(1), row.get(2))
            && t == table
        {
            out.push((col.clone(), sql.clone()));
        }
    }
    Ok(out)
}

/// Build a per-column fill vector for `table`, indexed by column ordinal: `Some(fill)` for a column
/// with a `DEFAULT` or `SERIAL`, `None` otherwise. A regular default's SQL is re-parsed
/// and analyzed to the column's type; a serial sentinel resolves its backing sequence. Returns an
/// all-`None` vector when the table has neither.
pub(super) fn column_fills(
    table: &TableSchema,
    engine: &dyn StorageEngine,
    txn: TxnId,
) -> Result<Vec<Option<ColumnFill>>, Error> {
    let stored = load_defaults(&catalog_key(&table.schema, &table.name), engine, txn)?;
    let mut fills: Vec<Option<ColumnFill>> = (0..table.columns.len()).map(|_| None).collect();
    if stored.is_empty() {
        return Ok(fills);
    }
    for (column, sql) in stored {
        let Some((index, col)) = table
            .columns
            .iter()
            .enumerate()
            .find(|(_, c)| c.name == column)
        else {
            continue;
        };
        let fill = if let Some(gen_sql) = generated_expr(&sql) {
            // A generated column's expression references this table's other columns, so analyze it
            // against the table scope (not the empty default scope) and re-evaluate it per row.
            ColumnFill::Generated(crate::analyzer::analyze_generated_expr(
                gen_sql,
                table,
                col.ty,
                &super::dml::EmptyCatalog,
            )?)
        } else if let Some(seq) = serial_sequence(&sql) {
            let id = engine.lookup_sequence(seq)?.ok_or_else(|| {
                Error::Unsupported(format!(
                    "serial column \"{column}\" has no backing sequence"
                ))
            })?;
            ColumnFill::Serial {
                id,
                always: sql.starts_with(IDENTITY_ALWAYS_PREFIX),
            }
        } else {
            ColumnFill::Expr(crate::analyzer::analyze_default_expr(
                &sql,
                col.ty,
                &super::dml::EmptyCatalog,
            )?)
        };
        if let Some(slot) = fills.get_mut(index) {
            *slot = Some(fill);
        }
    }
    Ok(fills)
}
