//! DDL statement types: CREATE/DROP/ALTER/TRUNCATE + constraints.
//!
//! Pure AST types split verbatim out of `ast/mod.rs` (ADR 007). Sibling types resolve via
//! `use super::*` (re-exported by the parent).
#![allow(clippy::wildcard_imports)]

use super::*;
use nusadb_core::ColumnType;

/// `CREATE TABLE name (columns...)`.
// Not `Eq`: a table-level `CHECK` constraint carries an `Expr`, which is only `PartialEq`.
#[derive(Debug, Clone, PartialEq)]
pub struct CreateTable {
    /// Explicit schema qualifier to create the table in: `Some(schema)` for `CREATE TABLE
    /// schema.t`, `None` when unqualified (created in the session's current schema).
    pub schema: Option<String>,
    /// Table name.
    pub name: String,
    /// Columns in declaration order; always non-empty.
    pub columns: Vec<ColumnDef>,
    /// Table-level constraints (`PRIMARY KEY`/`UNIQUE`/`FOREIGN KEY`/`CHECK`), in declaration order.
    pub constraints: Vec<TableConstraint>,
    /// Whether `IF NOT EXISTS` was specified.
    pub if_not_exists: bool,
}

/// `CREATE TABLE [IF NOT EXISTS] name AS <select>`.
///
/// The new table's schema is derived from the query's output (name + type per projected column); use
/// column aliases in the `SELECT` to name the output columns. The query's rows are inserted at
/// creation time.
// Not `Eq`: the `Select` body carries `Expr`s, which are only `PartialEq`.
#[derive(Debug, Clone, PartialEq)]
pub struct CreateTableAs {
    /// Table name.
    pub name: String,
    /// The source query — any supported `SELECT`.
    pub query: Box<Select>,
    /// Whether `IF NOT EXISTS` was specified.
    pub if_not_exists: bool,
}

/// One column definition inside a [`CreateTable`].
// Not `Eq`: `default`/`generated` carry an `Expr`, which is only `PartialEq`.
#[derive(Debug, Clone, PartialEq)]
#[allow(
    clippy::struct_excessive_bools,
    reason = "each bool is an independent column attribute (NULL/PK/UNIQUE/SERIAL), not a state flag"
)]
pub struct ColumnDef {
    /// Column name.
    pub name: String,
    /// Column type, mapped onto the catalog's [`ColumnType`] vocabulary.
    pub ty: ColumnType,
    /// A user-defined type name (e.g. an `ENUM` created by `CREATE TYPE`) the parser could not
    /// resolve to a built-in type, carried so the executor can resolve it against the type catalog at
    /// `CREATE TABLE` time (B-ENUM). `ty` holds the placeholder storage type (`TEXT`); `None` for an
    /// ordinary built-in type.
    pub udt_name: Option<String>,
    /// Whether the column accepts `NULL`. `NOT NULL` and `PRIMARY KEY` clear this.
    pub nullable: bool,
    /// Whether the column carries a `PRIMARY KEY` clause.
    pub primary_key: bool,
    /// Whether the column carries a (non-primary) `UNIQUE` clause.
    pub unique: bool,
    /// `DEFAULT <expr>` — value expression applied when the column is omitted.
    /// Boxed to keep `ColumnDef` small (it lives in `Vec<ColumnDef>` throughout the plan).
    pub default: Option<Box<Expr>>,
    /// The `DEFAULT` expression's canonical SQL text, carried alongside [`default`](Self::default) so
    /// the executor can persist it in the column-default catalog and re-parse it per write,
    /// mirroring how a `CHECK` predicate carries `predicate_sql`. `None` when there is no default.
    pub default_sql: Option<String>,
    /// `GENERATED ALWAYS AS (<expr>) [STORED|VIRTUAL]` — a computed column.
    pub generated: Option<GeneratedColumn>,
    /// `true` for a `SERIAL`/`BIGSERIAL`/`SMALLSERIAL` column: an auto-incrementing `INT`
    /// backed by a per-column sequence. Implies `NOT NULL`; an omitted value gets the next sequence
    /// value. Mutually exclusive with an explicit `DEFAULT`.
    pub serial: bool,
    /// `true` only for `GENERATED ALWAYS AS IDENTITY` (a stricter [`serial`](Self::serial)): an
    /// explicit value is rejected at `INSERT` (#9a). `SERIAL` and `GENERATED BY DEFAULT AS IDENTITY`
    /// leave this `false` (they accept an explicit value).
    pub identity_always: bool,
}

/// A `GENERATED ALWAYS AS (<expr>) [STORED|VIRTUAL]` computed column.
#[derive(Debug, Clone, PartialEq)]
pub struct GeneratedColumn {
    /// The generation expression (boxed to keep `ColumnDef` small).
    pub expr: Box<Expr>,
    /// The generation expression's canonical SQL text, captured at parse time so it can be persisted
    /// in the column catalog and re-analyzed against the table per write, as `DEFAULT` does.
    pub sql: String,
    /// `true` for `STORED`, `false` for `VIRTUAL` (or unspecified — virtual is the default).
    pub stored: bool,
}

/// `DROP TABLE name`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DropTable {
    /// Explicit schema qualifier: `Some(schema)` for `DROP TABLE schema.t`, `None` when
    /// unqualified (resolved through the search path).
    pub schema: Option<String>,
    /// Table name.
    pub name: String,
    /// Whether `IF EXISTS` was specified.
    pub if_exists: bool,
    /// Whether `CASCADE` was specified: FOREIGN KEYs on other tables that reference this one
    /// are dropped instead of blocking. Dependent plain views are not
    /// tracked — their reads fail loudly after the drop.
    pub cascade: bool,
}

/// `DROP INDEX [IF EXISTS] name`.
///
/// Only the bare single-index form is modelled. The
/// `DROP INDEX name ON table` form, `CASCADE`/`RESTRICT`, and dropping several
/// indexes in one statement are out of scope for the v1 parser surface; the
/// parser rejects multi-index drops with
/// [`Error::Unsupported`](crate::error::Error::Unsupported).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DropIndex {
    /// Index name.
    pub name: String,
    /// Whether `IF EXISTS` was specified.
    pub if_exists: bool,
}

/// `CREATE [OR REPLACE] VIEW name [(columns)] AS <select>`.
///
/// Only the plain form is modelled. `MATERIALIZED`, `TEMPORARY`,
/// `IF NOT EXISTS`, `WITH (...)`, and dialect-specific clauses (`CLUSTER BY`,
/// `COMMENT`, `TO`, `WITH NO SCHEMA BINDING`) are out of scope for the v1
/// parser surface and rejected with
/// [`Error::Unsupported`](crate::error::Error::Unsupported). The view body is
/// any supported `SELECT`; re-evaluation semantics belong to the analyzer.
#[derive(Debug, Clone, PartialEq)]
pub struct CreateView {
    /// View name.
    pub name: String,
    /// Whether `OR REPLACE` was specified.
    pub or_replace: bool,
    /// Whether `IF NOT EXISTS` was specified (an existing view or table of the same name makes
    /// the statement a no-op). Mutually exclusive with `OR REPLACE`.
    pub if_not_exists: bool,
    /// `MATERIALIZED` — the view body is computed and stored at creation time. A plain
    /// (non-materialized) view re-evaluates on read and is not yet implemented.
    pub materialized: bool,
    /// Explicit output column names; empty means "infer from the query".
    pub columns: Vec<String>,
    /// The view body — a supported `SELECT`.
    pub query: Box<Select>,
    /// The view body rendered back to canonical SQL, persisted so `REFRESH MATERIALIZED VIEW` can
    /// re-execute the definition. Captured from the original `SELECT` at parse time.
    pub definition_sql: String,
}

/// `DROP VIEW [IF EXISTS] name`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DropView {
    /// View name.
    pub name: String,
    /// Whether `IF EXISTS` was specified.
    pub if_exists: bool,
}

/// `CREATE TYPE name AS ENUM ('a', 'b', ...)` — a user-defined enumerated type (B-ENUM). Stored as a
/// catalog object; a column of this type is stored as `TEXT`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CreateEnum {
    /// Type name (unique within the catalog).
    pub name: String,
    /// The ordered, distinct label set.
    pub labels: Vec<String>,
}

/// `DROP TYPE [IF EXISTS] name` — drop a user-defined type (B-ENUM).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DropType {
    /// Type name.
    pub name: String,
    /// Whether `IF EXISTS` was specified.
    pub if_exists: bool,
}

/// When a trigger fires relative to the triggering write.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TriggerTiming {
    /// `BEFORE` — fire before the row is written (and before constraint checks).
    Before,
    /// `AFTER` — fire after the row has been written.
    After,
}

impl TriggerTiming {
    /// The canonical keyword, used for catalog persistence and diagnostics.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Before => "before",
            Self::After => "after",
        }
    }
}

/// The DML event a trigger fires on.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TriggerEvent {
    /// `INSERT`.
    Insert,
    /// `UPDATE`.
    Update,
    /// `DELETE`.
    Delete,
}

impl TriggerEvent {
    /// The canonical keyword, used for catalog persistence and diagnostics.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Insert => "insert",
            Self::Update => "update",
            Self::Delete => "delete",
        }
    }

    /// Parse a canonical keyword back into an event (catalog read). Unknown text → `None`.
    #[must_use]
    pub fn parse_keyword(text: &str) -> Option<Self> {
        match text {
            "insert" => Some(Self::Insert),
            "update" => Some(Self::Update),
            "delete" => Some(Self::Delete),
            _ => None,
        }
    }
}

/// Granularity of a trigger: per affected row, or once per statement.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum TriggerForEach {
    /// `FOR EACH ROW` — the action fires once per affected row, with `NEW`/`OLD` bound (the default
    /// when the clause is omitted, since that is the form that can reference the affected row).
    #[default]
    Row,
    /// `FOR EACH STATEMENT` — the action fires once per statement, with no `NEW`/`OLD` binding.
    Statement,
}

impl TriggerForEach {
    /// The canonical keyword, used for catalog persistence and diagnostics.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Row => "row",
            Self::Statement => "statement",
        }
    }
}

/// `CREATE [OR REPLACE] TRIGGER name {BEFORE|AFTER} {INSERT|UPDATE|DELETE}[ OR ...] ON table
/// [FOR EACH {ROW|STATEMENT}] [WHEN (cond)] <triggered-statement>`.
///
/// The triggered action is a single SQL data statement (stored verbatim as text) that may reference
/// the affected row through the `NEW.col` / `OLD.col` pseudo-columns, substituted with the row's
/// values when the trigger fires. `INSTEAD OF` triggers (which require updatable views) are
/// rejected at the parser.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CreateTrigger {
    /// Trigger name (unique per table).
    pub name: String,
    /// Whether `OR REPLACE` was specified — replace a same-named trigger on the table.
    pub or_replace: bool,
    /// When the trigger fires relative to the write.
    pub timing: TriggerTiming,
    /// The events it fires on (one or more, joined by `OR`); never empty.
    pub events: Vec<TriggerEvent>,
    /// The table the trigger is attached to.
    pub table: String,
    /// Per-row or per-statement granularity.
    pub for_each: TriggerForEach,
    /// The `WHEN (cond)` guard as raw SQL (may reference `NEW`/`OLD`), or `None` if omitted.
    pub when: Option<String>,
    /// The triggered action as raw SQL — a single data statement (may reference `NEW`/`OLD`).
    pub action: String,
}

/// `DROP TRIGGER [IF EXISTS] name ON table`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DropTrigger {
    /// Trigger name.
    pub name: String,
    /// The table the trigger is attached to.
    pub table: String,
    /// Whether `IF EXISTS` was specified.
    pub if_exists: bool,
}

/// `ALTER TRIGGER name ON table RENAME TO new_name` — rename a trigger in place.
///
/// Renaming is the only `ALTER TRIGGER` form (matching the reference surface); enabling and
/// disabling ride `ALTER TABLE ... {ENABLE|DISABLE} TRIGGER` instead
/// ([`AlterTableAction::EnableTrigger`]/[`AlterTableAction::DisableTrigger`]).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AlterTrigger {
    /// Current trigger name.
    pub name: String,
    /// The table the trigger is attached to.
    pub table: String,
    /// The new trigger name.
    pub new_name: String,
}

/// One declared parameter of a stored procedure.
///
/// An `IN` parameter (the default) is referenced in the body positionally as `$1`..`$n` (in `IN`-only
/// order). An `OUT` parameter is a named output: the body `SET`s a variable of that name, and `CALL`
/// returns the final values of all `OUT` parameters as a result row. The declared type is accepted
/// but not yet used to coerce the value (a follow-up).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProcedureParam {
    /// Parameter name (the `OUT` parameter is read back by this name).
    pub name: String,
    /// Declared parameter type.
    pub ty: ColumnType,
    /// `true` for an `OUT` parameter (a named output), `false` for an ordinary `IN` parameter.
    pub out: bool,
}

/// `CREATE [OR REPLACE] PROCEDURE name([p type, ...]) [LANGUAGE SQL] AS <body>`.
///
/// The body is one or more `;`-separated SQL data statements, stored verbatim as text. Statements
/// reference the call arguments positionally as `$1`..`$n` (reusing the prepared-statement parameter
/// machinery); `CALL` binds the arguments before each statement runs.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CreateProcedure {
    /// Procedure name (unique).
    pub name: String,
    /// Whether `OR REPLACE` was specified.
    pub or_replace: bool,
    /// Declared parameters, in order.
    pub params: Vec<ProcedureParam>,
    /// The procedure body as raw SQL (one or more `;`-separated statements).
    pub body: String,
}

/// `DROP PROCEDURE [IF EXISTS] name`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DropProcedure {
    /// Procedure name.
    pub name: String,
    /// Whether `IF EXISTS` was specified.
    pub if_exists: bool,
}

/// `CALL name(arg, ...)` — invoke a stored procedure with constant arguments.
#[derive(Debug, Clone, PartialEq)]
pub struct Call {
    /// The procedure name.
    pub name: String,
    /// Constant argument expressions, one per declared parameter, in order.
    pub args: Vec<Expr>,
}

/// `CREATE [OR REPLACE] FUNCTION name(p type, ...) RETURNS type [LANGUAGE SQL] AS <body>`.
///
/// The body is a `SELECT <expr>` whose single scalar projection references the parameters as
/// `$1`..`$n`. A call to the function is inlined: the body's expression (with arguments substituted
/// for the placeholders) is analyzed in place of the call.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CreateFunction {
    /// Function name (unique).
    pub name: String,
    /// Whether `OR REPLACE` was specified.
    pub or_replace: bool,
    /// Declared parameters, in order (all input; referenced as `$1`..`$n`).
    pub params: Vec<ProcedureParam>,
    /// The declared return type.
    pub return_type: ColumnType,
    /// The function body as raw SQL (`SELECT <expr>`).
    pub body: String,
}

/// `DROP FUNCTION [IF EXISTS] name`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DropFunction {
    /// Function name.
    pub name: String,
    /// Whether `IF EXISTS` was specified.
    pub if_exists: bool,
}

/// The command a row-level-security policy applies to. `ALL` covers every command.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PolicyCommand {
    /// `FOR ALL` — the policy applies to every command (the default when `FOR` is omitted).
    All,
    /// `FOR SELECT`.
    Select,
    /// `FOR INSERT`.
    Insert,
    /// `FOR UPDATE`.
    Update,
    /// `FOR DELETE`.
    Delete,
}

impl PolicyCommand {
    /// The canonical keyword, used for catalog persistence and diagnostics.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::All => "ALL",
            Self::Select => "SELECT",
            Self::Insert => "INSERT",
            Self::Update => "UPDATE",
            Self::Delete => "DELETE",
        }
    }
}

/// `CREATE POLICY name ON table [AS { PERMISSIVE | RESTRICTIVE }] [FOR command] [TO role[, ...]]
/// [USING (expr)] [WITH CHECK (expr)]` — a row-level-security policy.
///
/// `USING`/`WITH CHECK` expressions are captured as canonical SQL text and re-analyzed against the
/// target table. A permissive policy *grants* access (the applicable permissive policies are
/// `OR`-combined); a restrictive policy *narrows* it (the applicable restrictive policies are
/// `AND`-combined on top), following the SQL-standard row-level-security model.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CreatePolicy {
    /// Policy name (unique per table).
    pub name: String,
    /// The table the policy governs.
    pub table: String,
    /// `true` for `AS PERMISSIVE` (the default when `AS` is omitted); `false` for `AS RESTRICTIVE`.
    pub permissive: bool,
    /// The command the policy applies to.
    pub command: PolicyCommand,
    /// Roles the policy applies to; empty means `PUBLIC` (every role).
    pub roles: Vec<String>,
    /// The `USING (expr)` row-visibility predicate as canonical SQL, or `None` if omitted.
    pub using: Option<String>,
    /// The `WITH CHECK (expr)` write predicate as canonical SQL, or `None` if omitted.
    pub check: Option<String>,
}

/// `DROP POLICY [IF EXISTS] name ON table`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DropPolicy {
    /// Policy name.
    pub name: String,
    /// The table the policy is attached to.
    pub table: String,
    /// Whether `IF EXISTS` was specified.
    pub if_exists: bool,
}

/// `ALTER POLICY name ON table [TO role[, ...]] [USING (expr)] [WITH CHECK (expr)]`.
///
/// Each optional clause is `None` when omitted, meaning the existing policy keeps that part; a
/// `Some` replaces it. The policy's kind (permissive/restrictive) and command cannot be changed by
/// `ALTER POLICY` (matching the SQL-standard model), so they are not modelled here.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AlterPolicy {
    /// Policy name (must already exist on `table`).
    pub name: String,
    /// The table the policy is attached to.
    pub table: String,
    /// New `TO role[, ...]` list, or `None` to keep the existing roles. An empty list is `PUBLIC`.
    pub roles: Option<Vec<String>>,
    /// New `USING (expr)` predicate as canonical SQL, or `None` to keep the existing one.
    pub using: Option<String>,
    /// New `WITH CHECK (expr)` predicate as canonical SQL, or `None` to keep the existing one.
    pub check: Option<String>,
}

/// `CREATE SCHEMA [IF NOT EXISTS] name`.
///
/// Only the plain named form is modelled; the `AUTHORIZATION <role>` variants
/// are out of scope for the v1 parser surface and rejected with
/// [`Error::Unsupported`](crate::error::Error::Unsupported).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CreateSchema {
    /// Schema name.
    pub name: String,
    /// Whether `IF NOT EXISTS` was specified.
    pub if_not_exists: bool,
}

/// `DROP SCHEMA [IF EXISTS] name [CASCADE | RESTRICT]`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DropSchema {
    /// Schema name.
    pub name: String,
    /// Whether `IF EXISTS` was specified.
    pub if_exists: bool,
    /// `CASCADE` drops the schema's tables with it; the default (`RESTRICT`) refuses a non-empty
    /// schema.
    pub cascade: bool,
}

/// `CREATE DATABASE [IF NOT EXISTS] name` — a single-database compatibility no-op.
///
/// NusaDB is one database per data directory, so this does not isolate a new database; accepting it
/// lets portable scripts and tooling that open with `CREATE DATABASE` run unchanged.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CreateDatabase {
    /// Database name (recorded for the command tag / EXPLAIN; otherwise unused).
    pub name: String,
    /// Whether `IF NOT EXISTS` was specified.
    pub if_not_exists: bool,
}

/// `DROP DATABASE [IF EXISTS] name` — drop every table in the current single database.
///
/// NusaDB is one database per data directory, so this empties the data directory's tables rather
/// than isolating a separate database — but **only when `name` matches the current database**;
/// dropping any other name is a no-op (a non-matching database is left untouched). As a data-loss safety net (NusaDB
/// extension), the plain form first **backs up** every table — its columns *and* rows — to
/// `{name}_{datetime}_{table}` before dropping the originals. The canonical `DROP DATABASE name FORCE`
/// form (or the `FIX DROP DATABASE name` alias) sets [`force`](Self::force) to drop permanently
/// **without** a backup.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DropDatabase {
    /// Database name.
    pub name: String,
    /// Whether `IF EXISTS` was specified.
    pub if_exists: bool,
    /// `true` for `DROP DATABASE name FORCE` (or the `FIX DROP DATABASE name` alias) — drop
    /// permanently, skipping the safety backup.
    pub force: bool,
}

/// `ALTER DATABASE name ...` — a single-database compatibility no-op.
///
/// NusaDB has one database per data directory with no database-level options to alter, so any
/// `ALTER DATABASE` is accepted and ignored, letting ecosystem scripts run unchanged.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AlterDatabase {
    /// Database name (recorded for the command tag / EXPLAIN; otherwise unused).
    pub name: String,
}

/// `CREATE SEQUENCE [IF NOT EXISTS] name [options...]`.
///
/// `TEMPORARY`, `AS <type>`, and `OWNED BY` are out of scope for the v1 parser
/// surface and rejected with
/// [`Error::Unsupported`](crate::error::Error::Unsupported). The recognised
/// options are kept in declaration order.
#[derive(Debug, Clone, PartialEq)]
pub struct CreateSequence {
    /// Sequence name.
    pub name: String,
    /// Whether `IF NOT EXISTS` was specified.
    pub if_not_exists: bool,
    /// Options in declaration order; may be empty.
    pub options: Vec<SequenceOption>,
}

/// One option of a `CREATE SEQUENCE` statement.
#[derive(Debug, Clone, PartialEq)]
pub enum SequenceOption {
    /// `INCREMENT [BY] <n>`.
    Increment(Expr),
    /// `MINVALUE <n>` (`Some`) or `NO MINVALUE` (`None`).
    MinValue(Option<Expr>),
    /// `MAXVALUE <n>` (`Some`) or `NO MAXVALUE` (`None`).
    MaxValue(Option<Expr>),
    /// `START [WITH] <n>`.
    Start(Expr),
    /// `CACHE <n>`.
    Cache(Expr),
    /// `CYCLE` (`true`) or `NO CYCLE` (`false`).
    Cycle(bool),
}

/// `DROP SEQUENCE [IF EXISTS] name`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DropSequence {
    /// Sequence name.
    pub name: String,
    /// Whether `IF EXISTS` was specified.
    pub if_exists: bool,
}

/// `TRUNCATE [TABLE] name [RESTART IDENTITY | CONTINUE IDENTITY]`.
///
/// Only a single-table form is modelled. Multi-table truncation, `ONLY`,
/// partition lists, and `CASCADE`/`RESTRICT` are out of scope for the v1
/// parser surface and rejected with
/// [`Error::Unsupported`](crate::error::Error::Unsupported).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TruncateTable {
    /// Explicit schema qualifier (`Some` for `schema.name`), or `None` for a bare name resolved
    /// through the session search path.
    pub schema: Option<String>,
    /// Target table name (the last, unqualified component).
    pub name: String,
    /// `true` = `RESTART IDENTITY`, `false` = `CONTINUE IDENTITY` or unspecified.
    pub restart_identity: bool,
}

/// `ALTER TABLE [IF EXISTS] name <action>`.
///
/// Exactly one action per statement is modelled. Comma-separated multi-action
/// `ALTER TABLE`, `ONLY`, Hive `SET LOCATION`, and `ON CLUSTER` are out of
/// scope for the v1 parser surface and rejected with
/// [`Error::Unsupported`](crate::error::Error::Unsupported).
#[derive(Debug, Clone, PartialEq)]
pub struct AlterTable {
    /// Explicit schema qualifier (`Some` for `schema.name`), or `None` for a bare name resolved
    /// through the session search path.
    pub schema: Option<String>,
    /// Target table name (the last, unqualified component).
    pub name: String,
    /// Whether `IF EXISTS` was specified on the table.
    pub if_exists: bool,
    /// The single action to apply.
    pub action: AlterTableAction,
}

/// A single `ALTER TABLE` action.
///
/// Column actions (`ADD [COLUMN]`, `DROP [COLUMN]`, `RENAME COLUMN`,
/// `ALTER COLUMN`) and constraint actions (`ADD [CONSTRAINT]
/// <table_constraint>`, `DROP CONSTRAINT`) are modelled. Column positioning
/// (`FIRST`/`AFTER`) and `... CASCADE` are rejected by the parser.
#[derive(Debug, Clone, PartialEq)]
pub enum AlterTableAction {
    /// `ADD [COLUMN] [IF NOT EXISTS] <column_def>`.
    AddColumn {
        /// The column being added.
        column: ColumnDef,
        /// Whether `IF NOT EXISTS` was specified.
        if_not_exists: bool,
    },
    /// `DROP [COLUMN] [IF EXISTS] name` (implicit `RESTRICT`).
    DropColumn {
        /// Name of the column to drop.
        name: String,
        /// Whether `IF EXISTS` was specified.
        if_exists: bool,
    },
    /// `RENAME COLUMN from TO to`.
    RenameColumn {
        /// Current column name.
        from: String,
        /// New column name.
        to: String,
    },
    /// `RENAME TO name` — rename the table itself.
    RenameTable {
        /// The new table name.
        name: String,
    },
    /// `ADD [CONSTRAINT name] <table_constraint>`.
    AddConstraint(TableConstraint),
    /// `DROP CONSTRAINT [IF EXISTS] name` (implicit `RESTRICT`).
    DropConstraint {
        /// Name of the constraint to drop.
        name: String,
        /// Whether `IF EXISTS` was specified.
        if_exists: bool,
    },
    /// `ALTER [COLUMN] name <change>`.
    AlterColumn {
        /// Name of the column being altered.
        column: String,
        /// The modification to apply.
        change: ColumnChange,
    },
    /// `ENABLE ROW LEVEL SECURITY` — turn on row-level security for the table.
    EnableRowLevelSecurity,
    /// `DISABLE ROW LEVEL SECURITY` — turn off row-level security for the table.
    DisableRowLevelSecurity,
    /// `ENABLE TRIGGER {name | ALL}` — re-enable a disabled trigger (`None` = every trigger on
    /// the table).
    EnableTrigger {
        /// The trigger to enable, or `None` for `ALL`.
        name: Option<String>,
    },
    /// `DISABLE TRIGGER {name | ALL}` — stop a trigger from firing without dropping it (`None` =
    /// every trigger on the table).
    DisableTrigger {
        /// The trigger to disable, or `None` for `ALL`.
        name: Option<String>,
    },
}

/// A modification applied to an existing column by `ALTER [COLUMN]`.
///
/// `SET DATA TYPE ... USING <expr>` (a conversion expression) and
/// `ADD GENERATED ... AS IDENTITY` are out of scope for the v1 parser surface
/// and rejected with [`Error::Unsupported`](crate::error::Error::Unsupported).
#[derive(Debug, Clone, PartialEq)]
pub enum ColumnChange {
    /// `[SET DATA] TYPE <type>`.
    SetType(ColumnType),
    /// `SET DEFAULT <expr>` — carries the default expression and its canonical SQL text,
    /// like a column's `default_sql`, so the executor can persist + re-parse it.
    SetDefault {
        /// The default value expression (type-checked at analysis time).
        expr: Expr,
        /// The default's canonical SQL text, persisted in the column-default catalog.
        sql: String,
    },
    /// `DROP DEFAULT`.
    DropDefault,
    /// `SET NOT NULL`.
    SetNotNull,
    /// `DROP NOT NULL`.
    DropNotNull,
}

/// A table-level constraint, as carried by `ADD CONSTRAINT` (and, in future,
/// the table-constraint clause of `CREATE TABLE`).
///
/// Only the four standard constraint kinds are modelled. Index hints
/// (`USING <method>`, `KEY`/`INDEX` display, index options) and
/// deferrable-constraint characteristics are out of scope and rejected by the
/// parser with [`Error::Unsupported`](crate::error::Error::Unsupported).
#[derive(Debug, Clone, PartialEq)]
pub enum TableConstraint {
    /// `[CONSTRAINT name] PRIMARY KEY (columns)`.
    PrimaryKey {
        /// Optional constraint name.
        name: Option<String>,
        /// Key columns in declaration order; always non-empty.
        columns: Vec<String>,
    },
    /// `[CONSTRAINT name] UNIQUE (columns)`.
    Unique {
        /// Optional constraint name.
        name: Option<String>,
        /// Unique columns in declaration order; always non-empty.
        columns: Vec<String>,
    },
    /// `[CONSTRAINT name] FOREIGN KEY (columns) REFERENCES table (referred)
    /// [ON DELETE action] [ON UPDATE action]`.
    ForeignKey {
        /// Optional constraint name.
        name: Option<String>,
        /// Referencing columns in this table.
        columns: Vec<String>,
        /// Referenced (parent) table.
        foreign_table: String,
        /// Referenced columns in the parent table; empty means the parent's
        /// primary key.
        referred_columns: Vec<String>,
        /// `ON DELETE` action, if specified.
        on_delete: Option<ReferentialAction>,
        /// `ON UPDATE` action, if specified.
        on_update: Option<ReferentialAction>,
    },
    /// `[CONSTRAINT name] CHECK (expr)`.
    Check {
        /// Optional constraint name.
        name: Option<String>,
        /// The boolean predicate.
        expr: Expr,
        /// The predicate's canonical SQL text — persisted in the constraint catalog so
        /// the executor can re-parse and enforce it per row on later `INSERT`/`UPDATE`.
        predicate_sql: String,
    },
}

/// A referential action for a foreign key's `ON DELETE` / `ON UPDATE` clause.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ReferentialAction {
    /// `NO ACTION` — reject if dependent rows remain (default).
    NoAction,
    /// `RESTRICT` — reject immediately.
    Restrict,
    /// `CASCADE` — propagate the delete/update to dependent rows.
    Cascade,
    /// `SET NULL` — null out the referencing columns.
    SetNull,
    /// `SET DEFAULT` — reset the referencing columns to their default.
    SetDefault,
}

/// `CREATE [UNIQUE] INDEX [IF NOT EXISTS] name ON table (keys) [INCLUDE (cols)] [WHERE pred]`.
///
/// Supports plain-column keys, **functional/expression** keys (`(lower(s))`, `((a + b))`, in
/// `key_exprs`), and a **partial-index** `WHERE` predicate. Per-column `ASC`/`DESC` /
/// `NULLS FIRST`/`NULLS LAST` are rejected — only ascending indexes are built and ordered index
/// scans are not implemented, so accepting a direction would be a silent-lossy trap. `WITH (...)`,
/// `NULLS DISTINCT`, `CONCURRENTLY`, and operator classes are also rejected. `USING <method>` is
/// accepted only for the `hnsw` vector access method. An anonymous index (no name) is rejected —
/// names are required so the downstream catalog has a stable handle.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CreateIndex {
    /// Index name (required).
    pub name: String,
    /// Explicit schema qualifier of the target table: `Some(schema)` for `CREATE INDEX … ON
    /// schema.t`, `None` when unqualified (resolved through the search path).
    pub table_schema: Option<String>,
    /// Target table the index covers.
    pub table: String,
    /// Plain key column names in declaration order — for a plain-column index. Empty when the
    /// index keys on expressions (`key_exprs` is then non-empty). Exactly one of `columns` /
    /// `key_exprs` is non-empty.
    pub columns: Vec<String>,
    /// Key expressions in declaration order, as SQL text — for a functional/expression index.
    /// Empty for a plain-column index. Each is re-parsed and evaluated per row to build the key.
    pub key_exprs: Vec<String>,
    /// Partial-index `WHERE` predicate as SQL text; `None` for a full index. Only rows for which it
    /// is true are indexed.
    pub predicate: Option<String>,
    /// Optional non-key columns stored alongside the key (`INCLUDE (...)`),
    /// preserving declaration order. Empty when no `INCLUDE` clause was given.
    pub include: Vec<String>,
    /// `USING <method>` access method, folded to lowercase; `None` for the default
    /// (B-tree). Only `Some("hnsw")` is otherwise accepted — a vector index.
    pub using: Option<String>,
    /// Whether `UNIQUE` was specified.
    pub unique: bool,
    /// Whether `IF NOT EXISTS` was specified.
    pub if_not_exists: bool,
}
